GET http://127.0.0.1:8080/users
Content-Type: application/json
Accept-version: v1.0

> {%
    client.test("Request executed successfully", function (){
        client.assert(response.status === 200, "Response status is not 200");
    });

%}

###
// @no-cookie-jar
GET http://127.0.0.1:8080/users
Content-Type: application/json
Authorization: Basic user password
Accept-version: v1.0

> {%
    client.test("Request executed successfully", function (){
        client.assert(response.status === 200, "Response status is not 200");
    });

%}

###